---
- name: installing lamp
  hosts: webservers
  become: root

  tasks:
          - name: instwebservers lamp
            apt:
                    name:
                            - apache2
                            - mariadb-server
                            - mariadb-client
                            - php
                            - php-mysql
                    state: present
          - name: starting httpd
            service:
                    name: apache2
                    enabled: yes
                    state: started
          - name: starting mysql

            service:
                    name: mysqld
                    enabled: yes
                    state: started
          - name: copy index.php to destination document root
            
            copy:
                    src: /home/franclin/Desktop/project/index.php
                    dest: /var/www/html

