---
- name: install lamp
  apt:
      name:
        - apache2
        - mariadb-server
        - mariadb-client
        - php
        - php-mysql
      state: present
- name: enable httpd service
  service:
      name: apache2
      enabled: yes
      state: started
- name: start mysql
  service:
      name: mysqld
      enabled: yes
      state: started
